import SwiftUI

struct Billing2FASetupHeader: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Secure your account with an authenticator app")
                .subheadline(.semibold)
            
            Text("Scan the QR code or copy the secret, then enter the code generated by your app")
                .footnote()
                .secondary()
        }
    }
}

#Preview {
    Billing2FASetupHeader()
}
