import SwiftUI
import UIKit

struct BillingTwoFASetupSheet: View {
    @Environment(BillingTwoFAVM.self) private var vm
    @Environment(\.dismiss) private var dismiss
    
    let onEnabled: () async -> Void
    
    @State private var code = ""
    @State private var isLoading = false
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            header
            
            if vm.isLoading {
                HStack {
                    ProgressView()
                    Text("Preparing setup…")
                }
            } else if let setup = vm.setup {
                setupContent(setup)
            } else {
                VStack(alignment: .leading, spacing: 12) {
                    Text("Unable to start 2FA setup")
                        .secondary()
                    
                    retryButton
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding()
        .navigationTitle("Set up 2FA")
        .navigationBarTitleDisplayMode(.inline)
        .task {
            await vm.fetchSetup()
        }
    }
    
    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Secure your account with an authenticator app")
                .subheadline(.semibold)
            
            Text("Scan the QR code or copy the secret, then enter the code generated by your app")
                .footnote()
                .secondary()
        }
    }
    
    private func setupContent(_ setup: BillingTwoFASetupResponse) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            if let qr = generateQRCode(setup.url) {
                Image(uiImage: qr)
                    .resizable()
                    .scaledToFit()
                    .frame(maxWidth: 240)
                    .clipShape(.rect(cornerRadius: 12))
            }
            
            VStack(alignment: .leading, spacing: 8) {
                Text("Secret")
                    .footnote(.semibold)
                
                CopyableLabel(setup.secret)
            }
            
            VStack(alignment: .leading, spacing: 8) {
                Text("Code")
                    .footnote(.semibold)
                
                TextField("123456", text: $code)
                    .keyboardType(.numberPad)
                    .textContentType(.oneTimeCode)
            }
            
            if let error = vm.error {
                Text(error)
                    .foregroundStyle(.red)
                    .footnote()
            }
            
            Spacer()
            
            Button {
                enableTwoFA()
            } label: {
                if vm.isEnabling || isLoading {
                    ProgressView()
                } else {
                    Text("Enable 2FA")
                }
            }
            .frame(maxWidth: .infinity)
            .buttonStyle(.borderedProminent)
            .disabled(code.trimmingCharacters(in: .whitespaces).count < 6 || vm.isEnabling || isLoading)
        }
    }
    
    private var retryButton: some View {
        Button {
            Task {
                await vm.fetchSetup()
            }
        } label: {
            if vm.isLoading {
                ProgressView()
            } else {
                Text("Retry")
            }
        }
    }
    
    private func enableTwoFA() {
        Task {
            isLoading = true
            let success = await vm.enable(code: code.trimmingCharacters(in: .whitespaces))
            isLoading = false
            
            if success {
                await onEnabled()
                dismiss()
            }
        }
    }
    
    private func generateQRCode(_ text: String) -> UIImage? {
        let data = text.data(using: .utf8)
        
        guard let qrFilter = CIFilter(name: "CIQRCodeGenerator") else {
            return nil
        }
        
        qrFilter.setValue(data, forKey: "inputMessage")
        qrFilter.setValue("M", forKey: "inputCorrectionLevel")
        
        guard let qrImage = qrFilter.outputImage else {
            return nil
        }
        
        let transform = CGAffineTransform(scaleX: 8, y: 8)
        let scaledQRImage = qrImage.transformed(by: transform)
        
        let context = CIContext()
        
        guard let cgImage = context.createCGImage(scaledQRImage, from: scaledQRImage.extent) else {
            return nil
        }
        
        return UIImage(cgImage: cgImage)
    }
}

struct CopyableLabel: View {
    private let value: String
    
    init(_ value: String) {
        self.value = value
    }
    
    var body: some View {
        HStack {
            Text(value)
                .monospaced()
                .lineLimit(1)
                .minimumScaleFactor(0.5)
            
            Spacer()
            
            Button {
                UIPasteboard.general.string = value
                SystemAlert.copied("Copied")
            } label: {
                Image(systemName: "doc.on.doc")
            }
            .buttonStyle(.bordered)
        }
        .padding()
        .background(.thinMaterial, in: .rect(cornerRadius: 10))
    }
}
